= SETTING UP CREDENTIALS AND SOURCES

== Credential settings

To prepare Discovery to run scans, you must add the parts of your IT infrastructure that you want to scan as one or more sources. You must also add the authentication information, such as a username and password or SSH key, that is required to access those sources as one or more credentials. Because of differing configuration requirements, you add sources and credentials according to the type of source that you are going to scan

== How to add credentials and sources

Here the official documentation on how to setup the credentials and sources for each type of scan: https://docs.redhat.com/en/documentation/subscription_central/1-latest/html-single/using_red_hat_discovery/index#assembly-adding-net-sources-creds-gui



== Launching the Scan   

Once the credentials and sources have been set up correctly, we can run the scan.
Scans can be launched by clicking on the three dots that are on the right side of the sources page/line.
Once a Scan is launched, it will appear in the scan tab menu of the UI.

== Downloading the inventory report

Once a scan finalize, it will appear with a green tick (meaning successful scan) in the scan tab of the UI.
On that line you will need to click on the three dots that are on the right side of the scan line and click on Download.
A folder will be stored locally in your Discovery machine with inside the invetory reports that the Discovery created.
